### ISSUE TITLE
Transparency issues

### ISSUE THREAD

**Issue by delonleo** [RoadrunnerWMC/libimagequant-python#1]
Hi,

Appreciate your good work.

Was wondering the reason for such result ? Thank you.

![test](https://user-images.githubusercontent.com/6275034/95560790-5680b580-0a4c-11eb-880a-ca12d79a485e.png)

![example](https://user-images.githubusercontent.com/6275034/95560862-6e583980-0a4c-11eb-8714-f4603971552a.png)

**Comment by RoadrunnerWMC** [comment]
Hi; thank you!

PIL's support for paletted images with transparency (the `"PA"` [image mode](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#concept-modes)) is really bad in my experience, so the examples in the documentation save the output image using the `"P"` mode (with no transparency support) instead. I'll add a note to the documentation to make that more clear.

If you need to handle transparency, I recommend using PyQt5 for loading/saving images instead of PIL. You might want to check out my separate "[libimagequant-python-integrations](https://github.com/RoadrunnerWMC/libimagequant-python-integrations)" module that can perform the conversions to/from libimagequant classes for you.

Hope that helps! Let me know if you have any more questions.

**Comment by RoadrunnerWMC** [comment]
Actually, scratch that. I just tested it with PyQt5 and the result is the same. I'll try to come up with a better solution...

**Comment by RoadrunnerWMC** [comment]
All right! Here's a verified working example using the [pypng](https://pypi.org/project/pypng/) library. Since Pillow and PyQt5 don't support paletted transparent PNGs well or at all, I think I'll actually replace Pillow with this in the documentation examples and add support for it to libimagequant_integrations.

```python
import libimagequant as liq
import png

# Load the image with pypng
img = png.Reader(filename='input.png')
width, height, data, info = img.read_flat()

# Create libimagequant Attr and Image objects from it
attr = liq.Attr()
input_image = attr.create_rgba(data, width, height, info.get('gamma', 1.0))

# Quantize
result = input_image.quantize(attr)

# Get the quantization result
out_pixels = result.remap_image(input_image)
out_palette = result.get_palette()

# Save it
w = png.Writer(input_image.width, input_image.height, palette=out_palette)
with open('output.png', 'wb') as f:
    w.write_array(f, out_pixels)
```

**Comment by RoadrunnerWMC** [comment]
The documentation has been updated, and I've released [a new version of libimagequant-integrations](https://github.com/RoadrunnerWMC/libimagequant-python-integrations/releases/tag/v1.1.0) that handles transparency correctly (except for Pillow, which itself doesn't support it well) and adds integration with PyPNG.

**Comment by delonleo** [comment]
🙏 It's perfect now .
